# Generated by Django 2.2.5 on 2019-09-05 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
                ('link', models.URLField(null=True)),
                ('attachment', models.URLField(null=True)),
                ('images', models.URLField(null=True)),
                ('claps', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Rejected')], default=1)),
                ('privacy_level', models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Slow'), (2, 'Blocked')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField(blank=True)),
                ('link', models.URLField(null=True)),
                ('images', models.URLField(null=True)),
                ('claps', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_comment', to='story.Story')),
            ],
        ),
    ]
