# Generated by Django 2.2 on 2019-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='privacy_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Self'), (1, 'Friends'), (2, 'Public')], default=0),
        ),
    ]
