# Generated by Django 2.2 on 2019-09-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0002_auto_20190926_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time_created',
            new_name='ts_created',
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='ts_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='story',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='privacy_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Self'), (1, 'Friends'), (2, 'Public')], default=2),
        ),
    ]
