# Generated by Django 2.2 on 2019-09-26 11:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20190926_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='story',
            name='attachment',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='images',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
